kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: aktivitet-arena-acl
  namespace: dab
  labels:
    team: dab
spec:
  image: ghcr.io/navikt/aktivitet-arena-acl/aktivitet-arena-acl:{{version}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 4
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-aktivitetskort-publisher
          namespace: amt
          cluster: prod-gcp
    outbound:
      rules:
        - application: amt-enhetsregister
          namespace: amt
          cluster: prod-gcp
      external:
        - host: amt-arena-ords-proxy.prod-fss-pub.nais.io
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: dab-unleash-api.nav.cloud.nais.io
  env:
    - name: AMT_ARENA_ORDS_PROXY_SCOPE
      value: api://prod-fss.amt.amt-arena-ords-proxy/.default
    - name: AMT_ARENA_ORDS_PROXY_URL
      value: https://amt-arena-ords-proxy.prod-fss-pub.nais.io
    # Kafka topics
    - name: AKTIVITETSKORT_TOPIC
      value: dab.aktivitetskort-v1.1
    - name: ARENA_TILTAK_TOPIC
      value: teamarenanais.aapen-arena-tiltakendret-v1-p
    - name: ARENA_TILTAKGJENNOMFORING_TOPIC
      value: teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-p
    - name: ARENA_TILTAK_DELTAKER_TOPIC
      value: teamarenanais.aapen-arena-tiltakdeltakerendret-v1-p
    - name: AMT_ENHETSREGISTER_SCOPE
      value: api://prod-gcp.amt.amt-enhetsregister/.default
    - name: AMT_ENHETSREGISTER_URL
      value: http://amt-enhetsregister.amt.svc.cluster.local
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://prod-fss.pto.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.prod-fss-pub.nais.io
    - name: UNLEASH_ENVIRONMENT
      value: production
  gcp:
    sqlInstances:
      - name: aktivitet-arena-acl-v1
        type: POSTGRES_14
        tier: db-custom-1-3840
        diskAutoresize: true
        pointInTimeRecovery: true
        databases:
          - name: aktivitet-arena-acl
            envVarPrefix: DB
