kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: aktivitet-arena-acl
  namespace: dab
  labels:
    team: dab
spec:
  image: ghcr.io/navikt/aktivitet-arena-acl/aktivitet-arena-acl:{{version}}
  port: 8080
  ingresses:
    - https://aktivitet-arena-acl.intern.dev.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: amt-aktivitetskort-publisher
          namespace: amt
          cluster: dev-gcp
    outbound:
      rules:
        - application: amt-enhetsregister
          namespace: amt
          cluster: dev-gcp
      external:
        - host: amt-arena-ords-proxy.dev-fss-pub.nais.io
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: dab-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: veilarbaktivitet-unleash-api-token
  env:
    # q2: api://dev-fss.amt.amt-arena-ords-proxy/.default q1: api://dev-fss.amt.amt-arena-ords-proxy-q1/.default
    - name: AMT_ARENA_ORDS_PROXY_SCOPE
      value: api://dev-fss.amt.amt-arena-ords-proxy/.default
    # q2: https://amt-arena-ords-proxy-q1.dev-fss-pub.nais.io q1: https://amt-arena-ords-proxy.dev-fss-pub.nais.io
    - name: AMT_ARENA_ORDS_PROXY_URL
      value: https://amt-arena-ords-proxy.dev-fss-pub.nais.io
    # Kafka topics
    - name: AKTIVITETSKORT_TOPIC
      value: dab.aktivitetskort-v1.1
    - name: ARENA_TILTAK_TOPIC
      value: teamarenanais.aapen-arena-tiltakendret-v1-q2
    - name: ARENA_TILTAKGJENNOMFORING_TOPIC
      value: teamarenanais.aapen-arena-tiltakgjennomforingendret-v1-q2
    - name: ARENA_TILTAK_DELTAKER_TOPIC
      value: teamarenanais.aapen-arena-tiltakdeltakerendret-v1-q2
    - name: AMT_ENHETSREGISTER_SCOPE
      value: api://dev-gcp.amt.amt-enhetsregister/.default
    - name: AMT_ENHETSREGISTER_URL
      value: http://amt-enhetsregister.amt.svc.cluster.local
    - name: VEILARBOPPFOLGING_SCOPE
      value: api://dev-fss.pto.veilarboppfolging/.default
    - name: VEILARBOPPFOLGING_URL
      value: https://veilarboppfolging.dev-fss-pub.nais.io
    - name: UNLEASH_ENVIRONMENT
      value: development
  gcp:
    sqlInstances:
      - name: aktivitet-arena-acl-v1
        type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: aktivitet-arena-acl
            envVarPrefix: DB
