apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: aktivitet-arena-acl
  namespace: dab
  labels:
    team: dab
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: dab
  secretName: aktivitet-arena-acl-unleash-api-token
  environment: production
