name: Deploy application
on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ghcr.io/${{ github.repository }}/aktivitet-arena-acl
  PRINT_PAYLOAD: true

jobs:
  test-build-and-push:
    name: Test, build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build maven artifacts
        run: mvn -B package
      - name: Build and push Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${GITHUB_REPOSITORY} --password-stdin
          docker build -t ${IMAGE}:${IMAGE_TAG} .
          docker push ${IMAGE}:${IMAGE_TAG}

  deploy-dev:
    name: Deploy to dev
    needs: test-build-and-push
    uses: ./.github/workflows/naisdeploy.yaml
    with:
      environment: dev
    secrets:
      nais-deploy-secret: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-prod:
    name: Deploy to prod
    needs: test-build-and-push
    uses: ./.github/workflows/naisdeploy.yaml
    with:
      environment: prod
    secrets:
      nais-deploy-secret: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
