on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      nais-deploy-secret:
        required: true
      github-token:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application to ${{ inputs.environment }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.nais-deploy-secret }}
          CLUSTER: ${{ inputs.environment }}-gcp
          RESOURCE: .nais/nais-${{ inputs.environment }}.yaml
          VAR: version=${{ github.sha }}
