on:
  workflow_call:
    inputs:
      VAR:
        type: string
        required: true
      TELEMETRY:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      nais-deploy-secret:
        required: true
      github-token:
        required: true
      SLACK_WEBHOOK:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application to ${{ inputs.environment }}
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.environment }}-gcp
          RESOURCE: .nais/nais-${{ inputs.environment }}.yaml
          VAR: ${{ inputs.VAR }}
          TELEMETRY: ${{ inputs.TELEMETRY }}
      - name: Slack Notification (deploy failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Veilarbdialog: deploy feilet!'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Commit-message til feilende deploy: ${{ github.event.head_commit.message }}'
